//go:build go1.22

// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package apitypes

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all supervised apps
	// (GET /v1/apps)
	ListApps(w http.ResponseWriter, r *http.Request)
	// Spawn a new supervised app
	// (POST /v1/apps)
	SpawnApp(w http.ResponseWriter, r *http.Request)
	// Stop and remove an app
	// (DELETE /v1/apps/{id})
	StopApp(w http.ResponseWriter, r *http.Request, id AppID)
	// Get app details (k8s-style envelope)
	// (GET /v1/apps/{id})
	GetApp(w http.ResponseWriter, r *http.Request, id AppID)
	// Blue-green deploy a new version
	// (POST /v1/apps/{id}/deploy)
	DeployApp(w http.ResponseWriter, r *http.Request, id AppID)
	// SSE stream of app state transitions
	// (GET /v1/apps/{id}/events)
	GetAppEvents(w http.ResponseWriter, r *http.Request, id AppID)
	// Read app log output
	// (GET /v1/apps/{id}/logs)
	GetAppLogs(w http.ResponseWriter, r *http.Request, id AppID, params GetAppLogsParams)
	// Reset a crash-looping app
	// (POST /v1/apps/{id}/reset)
	ResetApp(w http.ResponseWriter, r *http.Request, id AppID)
	// Restart an app
	// (POST /v1/apps/{id}/restart)
	RestartApp(w http.ResponseWriter, r *http.Request, id AppID)
	// Get cgroup resource stats
	// (GET /v1/apps/{id}/stats)
	GetAppStats(w http.ResponseWriter, r *http.Request, id AppID)
	// List all registered volumes
	// (GET /v1/volumes)
	ListVolumes(w http.ResponseWriter, r *http.Request)
	// Register a persistent volume
	// (POST /v1/volumes)
	RegisterVolume(w http.ResponseWriter, r *http.Request)
	// Delete a volume
	// (DELETE /v1/volumes/{id})
	DeleteVolume(w http.ResponseWriter, r *http.Request, id VolumeID, params DeleteVolumeParams)
	// Get volume details
	// (GET /v1/volumes/{id})
	GetVolume(w http.ResponseWriter, r *http.Request, id VolumeID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListApps operation middleware
func (siw *ServerInterfaceWrapper) ListApps(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListApps(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SpawnApp operation middleware
func (siw *ServerInterfaceWrapper) SpawnApp(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SpawnApp(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StopApp operation middleware
func (siw *ServerInterfaceWrapper) StopApp(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AppID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StopApp(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApp operation middleware
func (siw *ServerInterfaceWrapper) GetApp(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AppID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApp(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeployApp operation middleware
func (siw *ServerInterfaceWrapper) DeployApp(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AppID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeployApp(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAppEvents operation middleware
func (siw *ServerInterfaceWrapper) GetAppEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AppID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAppEvents(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAppLogs operation middleware
func (siw *ServerInterfaceWrapper) GetAppLogs(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AppID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAppLogsParams

	// ------------- Optional query parameter "tail" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tail", r.URL.Query(), &params.Tail, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "tail"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tail", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "follow" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "follow", r.URL.Query(), &params.Follow, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "follow"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "follow", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAppLogs(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResetApp operation middleware
func (siw *ServerInterfaceWrapper) ResetApp(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AppID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResetApp(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RestartApp operation middleware
func (siw *ServerInterfaceWrapper) RestartApp(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AppID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RestartApp(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAppStats operation middleware
func (siw *ServerInterfaceWrapper) GetAppStats(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AppID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAppStats(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListVolumes operation middleware
func (siw *ServerInterfaceWrapper) ListVolumes(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListVolumes(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterVolume operation middleware
func (siw *ServerInterfaceWrapper) RegisterVolume(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterVolume(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteVolume operation middleware
func (siw *ServerInterfaceWrapper) DeleteVolume(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id VolumeID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteVolumeParams

	// ------------- Optional query parameter "force" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "force", r.URL.Query(), &params.Force, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "force"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "force", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteVolume(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVolume operation middleware
func (siw *ServerInterfaceWrapper) GetVolume(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id VolumeID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVolume(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/apps", wrapper.ListApps)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/apps", wrapper.SpawnApp)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/v1/apps/{id}", wrapper.StopApp)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/apps/{id}", wrapper.GetApp)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/apps/{id}/deploy", wrapper.DeployApp)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/apps/{id}/events", wrapper.GetAppEvents)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/apps/{id}/logs", wrapper.GetAppLogs)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/apps/{id}/reset", wrapper.ResetApp)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/apps/{id}/restart", wrapper.RestartApp)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/apps/{id}/stats", wrapper.GetAppStats)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/volumes", wrapper.ListVolumes)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/volumes", wrapper.RegisterVolume)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/v1/volumes/{id}", wrapper.DeleteVolume)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/volumes/{id}", wrapper.GetVolume)

	return m
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"3Ftdchs5kr5KRu08dO8UKapl93TLMQ+0pfYqbMsO0e6NDUvLAQtJFkYoAAZQlDkORuwh9g57jz3KnmQD",
	"QBVZRYI/Uutnwk82RfwkMr/8MpEJfksyWSgpUFiTHH9LFNGkQIvaf+ordXbi/kPRZJopy6RIjt2fgVEU",
	"lo0Zavjh5HzQ4WSEHMZSF8T+mKQJcwMVsXmSJoIUmBwnjCZpovFLyTTS5NjqEtPEZDkWxO1RkK9vUUxs",
	"nhz/fJQmBRP1x59St5JF7db8z8+k849e59er6t/O1b/Wf/lTkiZ2ptxexmomJsl8nia/S14WGDtH+KZx",
	"lDvJvbrj3A02SgqDXokvCb3ALyUa6z5lUlgU/r9EKc4y4oQ5+LtxEn1rLPsnjePkOPmXg6WBDsK35uBU",
	"a6kvqk3Clu2TnYkp4YyCrjaep8m5tL/JUtDHE+ICjSx1hiCkhbHfe54mnwQpbS41+wc+oizvmDFMTEBq",
	"YJVuRkg0arDyGoUHSrVYBfx1uLz5xXSMnXEEXZ8MxRS5VNiFASKcnA7OXp93DPJxJ5fGdowlFrsFvRSX",
	"ycccgQmLWqqO29pJY8qRQXuZOL8BmyOMGXIKBgsiLMtM91IkaaK0VKgtC3Aiiv2O2rCgHhRlkRx/TjKN",
	"eN2lOD2YHhKucnKYXK05Q5pcswCAepo7Z2xcgZZQYnfqva/Uu3qo06DCbI8pAzfMDbfElmafCWFgcK3a",
	"Dz83VVEdrSF5Jc1il+Ux5ejvmHmf6Ct1Oq3At6plNWQ04t5pkiPhNh+OCeOlDqMD7TmqEPbnZ0sWcvae",
	"oHazVGu15hdS2/g3Go0l2g4zWYoNQ5YaXBPTtiWjxGLHsgKTiLnDH3a4mFPURzdwnial5jHqa5vHf5vW",
	"qvQSbTDCuwbc2nbINHo++MgKp40i4pYXv706Ojr6tQtnRVFaMuL4ApRGg3qKFEimpTHOY63U2E3SPVUy",
	"QYGa2MrN2ju+LAtlQArAKeoZmDLL0JhxycFBDm40s9iF8/cfYVQWCqkbGiyVAhFCWr+uSR0b+bhpWnLV",
	"ICqYYIXz014MUCE4rYr2b2VBREcjoU4RcHaSwiJOwmHn5yPIcqL9fmtHrlmtQS/txd8r8qVEeNUfBNbs",
	"wivOHEjg3afBR39gKoFoZvMCLcvcuZmN7lUGd2iv/+nT2cn0L10YeCsuTeeO+gKE0zZoLA3Slr7KMsBr",
	"Kxi9usK+LeOuHzuNgG4DbgcV37WPcYLG7QqB/WGANpxnNIMs6Ku7zup64v9lFosN/hz+QLQmM/c5k0VB",
	"RJyiUExvt9gWEiqFd5Got0d1sqCkFfCMKo9cqEVPUXecs1gUL2rVgMYM2RThWe+5w493pojCslJrFPbD",
	"Jlqtv994sEDjv92OxQXaMxXVqKyO93oLb7wlxgaKWALQh32KissZjLm8gZwYyKSYop4gBSuBQBB1FjQH",
	"UkTZIhJZcmIiFHERLFrb4fz9x1P4v//6b/DDgRl484uBw+7hUYei0pgRi/QFWE2ya6SXIkeNi3wlI5yN",
	"qoN8uICbnHH0X1wgR7ccRzpBDX++FJkUlHneA4qGTQRwIqgBg+7OYZHPQhL1sv/qzdv3r7sFhf6Hs07v",
	"LyEJqjMWHxKdzj00RfhfponJh1xK5eO9VCr83f8XaTTFqaLrq83BtVROT+/2w8YK3UTgUBskbWK3DdQV",
	"qdZA2pBpAyP9zvAmks08LbvcLWPakH4JtEMW98GHybEaDLgtP6rcqp2V1agtxbWQNyJkoxvwi7T+X8ch",
	"uY3gNClFRQNRNAdcDIs7gTXgsLJ4pa3FKYJamzusam3dwDFwnniOa9yEHxaiVs/uB7wTTTIcl3w4PdxX",
	"vQuFZDlm10NfTYhtxVnB7M77z9swqoa+kXwRXqoVR1JyJCIgnfOhv2ZOCd9f3tpBCvI1pJw/P39+9LyR",
	"gh6mUechdDZ0sJCl3X+zOzgUEXQkv+6aMaiGzdNk6ks7w8IBtI2rbQuEgtA7j+o1KKw4jVdZDOi+FvFK",
	"UmwSwIjQYV2Mcb7cqIGkiZB2GOojDtVizFnmRhEeFLzkCbfnsDGiKmWE61X9oVZvmoS0YrhkjtSbQQvC",
	"oyTSrqKs38WqM+0sxPjDO19zH3bfE/269eioRhdXz4ZGAz0Ns5yICYYKHaGzNTJaslWSJlIWw2vG46d/",
	"u/DGlWOrcqhQM0mH5b4Qd3O+lNKS/acUWEg9G+Zskg9HM4u3nFeQr7eaphg1btK+8WLNKG+ZsX2lzGa8",
	"EKX2d706d9nldn7Rqw3yBP/dIlKghdsSwl6C1UvHZLsICNwY/G5JoTFzXCxJdcE5pfDkQgMXCBmF/WDJ",
	"rSu4z7WUNhq4mMqG7kJtFMkwHog88+4aJORQ4M1QaTY1G+IZo7sWKQ3qnWOs2T4kptKBIjfinyVhWSlF",
	"n/7HX3/vv/10Coow7VKyW2fjO3KTkEo/SE/mgRKfO2Uw30UqwhZZe4x8BpZYE78XZhMtSzVEQUYcaVyx",
	"LpSVhkxwWJpQ7br73a2KVdWV9zHCXB3xbxUWK/n2TWeR0CHqPRKdcM9q6zxmsabt12zmt5OCz+LmMuVo",
	"s1NboicYp/QKpVHDRSNdVdMPK24+xUb+HJHsmonJLgaK1G22nD+m8NZGmwWNe8hOKcdmWHdPnuoEzuqY",
	"lZrZ2cCxRyW5b2/2yyB3O3y8ujg9fXMy7J+8Ozsffnz/5vQ8qdqfXhY/c4n13FoVeqpMjOX6ah+0zNAY",
	"MKVCPWVGaiC0YAL6H858pdA3J2n3UvQ5BxRUSRYqvf6c8LLRiAV3MUJhqzYw3OQoYF1cYAYM2lAatMxy",
	"J2fYBvr13kmaTOtWRtLrHnZ7nhEUCqJYcpwcdXvdo8THsdyr7GB6eFAnrZWfOCx4Sc5ocrzIeZOVFv9P",
	"vd69tbLX8upIN9uNATkGL+w8TZ71Djctu5DzoNV496Api4K4rCOsRzhfmBBpWNs5uEtz6rzbB1oT0YzP",
	"lfpKVS8l0NiXks7uTSmtVGzedhKrS5yvGeTw3vZe3EzW7dBXCowTDWmjC8hnwSa93TZpvA25mxndpF8f",
	"7xmFO3BVloCqLAFSg8s9YFGXaGPLmw4ICLxZgdc6uubpwgcPvjE6D1zD0WIEcVaqGnAtyz+LP1iqK6l3",
	"1/Oz3ZMWj2xWdGClAiIoaCzkFIGI+PnTmnZWH9LYUgvjGyvuKIvnJyy0j65/MXDDNHZCtrJ4lXIp/vZt",
	"+UYihWsmaAr1C4nUt6LSqjM9/1sXPubMOGa1OV6KMdPGLtgarITShN5OvTyYnCh8AbXvw5+hJq9LYSzj",
	"HLSX3M/iOCHZDCpvCnOBlv4dTHPVS6FxTDIrNfxw49bgTnEKdScngnLUIKeow9OZLyUKCx8uzI/dS7H1",
	"BQ787/9sf4ITQkkbYq/RRhHWu09u2eRmtT6eBLCv0TqEAkVLGDfww/Xi7VMt14/R4NB4Pvg5vvdyyEF4",
	"Xji/WnX7g1C4XH2PuP+Cm6JU6EE8XJhq9zj2ilO9x4hTQS5wkxyZpp6Mq9wIOJvi4wasW+HykSPch2Yo",
	"c7Gt6s3XUY8JUFpONBqfeT3v/fR4sp03rDYmjCOtngaAL+as+PBLXmJnohHF4gxNu++Ovgc4rZ8FR7Ph",
	"QI+nYdBOYFv8asOKHWM1kuJWyA7P9CI6qZ6RDFwgCKJAtfyTBPrBabV9lZ5XbzasJsKE1w8PSJtcTnZZ",
	"660bsrbhCszKYuTC7Bg4E2hgrGVRhWhav5D+UqKeLZ9IuyiRNB9FUxyTktvk+LDXS5dFucNez3/e8rJt",
	"nq7KMwgKddgNAhEDTtFYIy8m0VhyLm9aMtV1cUfEkVK4Cxt/DMORB1JuguKEie0j12D978zmsrQQjnEM",
	"y4Xghtk8ZFTEWDgPOuleCjelGv9Xd8RqUlPcMJcJZhnh4IzmFgohAEpFifUrPYnrXCDxtwLgcgKytKq0",
	"D+gqGk1wkvtNMC7csg+fM267j/qTVZcN33UKponei7y44eaKFCmMypD2MQNCApdigjq8pRXfa7zv18e1",
	"0H57s4pOr9X2mP0usQd1//kh0OYWfrh8dqVvOV//ccvjAnsJ5yegJ7/7xqv7mtVd4N8VjX1r5iG5Ytn7",
	"2fb7nCDqU90zQ0NkWdQwlVLul/obnf+Npd3q+cBDV3dXXylsKfDWUt9njVfjhBmLGuli+aWyF68Y5ptJ",
	"J0wPp3gg4mn3jh654Nt89LFumupHg0stfrfF3uqk9c0XvzJjzRotBjUAAeXulcbJVeEqCqu2O+6s8p74",
	"vy+wtvXe8pt09BFW8pcDYKFFAhrHqFFkCDZnZile/OKgM/yD94ZnG39rGqSj32kyVf+gVvha8WjZIwiN",
	"qhZygmWBbANLujF4NtjngZh6Lxao6qNPFjunbTE28Pit4ubi59Lzq2Zn2U9t9pQ/Xzng+185RL3xJFQA",
	"gMuM8KohTCj1hbPqB4S+s3x8cOCH5NLY4197v/R8wludI9LIqc0JnI0xm2UcoSCCTLBA/xa9cuOqNbrW",
	"q14lqejkRdi9mv9/AAAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
