//go:build go1.22

// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package apitypes

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all supervised apps
	// (GET /v1/apps)
	ListApps(w http.ResponseWriter, r *http.Request)
	// Spawn a new supervised app
	// (POST /v1/apps)
	SpawnApp(w http.ResponseWriter, r *http.Request)
	// Stop and remove an app
	// (DELETE /v1/apps/{id})
	StopApp(w http.ResponseWriter, r *http.Request, id AppID, params StopAppParams)
	// Get app details (k8s-style envelope)
	// (GET /v1/apps/{id})
	GetApp(w http.ResponseWriter, r *http.Request, id AppID)
	// Blue-green deploy a new version
	// (POST /v1/apps/{id}/deploy)
	DeployApp(w http.ResponseWriter, r *http.Request, id AppID, params DeployAppParams)
	// SSE stream of app state transitions
	// (GET /v1/apps/{id}/events)
	GetAppEvents(w http.ResponseWriter, r *http.Request, id AppID)
	// Read app log output
	// (GET /v1/apps/{id}/logs)
	GetAppLogs(w http.ResponseWriter, r *http.Request, id AppID, params GetAppLogsParams)
	// Reset a crash-looping app
	// (POST /v1/apps/{id}/reset)
	ResetApp(w http.ResponseWriter, r *http.Request, id AppID)
	// Restart an app
	// (POST /v1/apps/{id}/restart)
	RestartApp(w http.ResponseWriter, r *http.Request, id AppID)
	// Roll back to a prior release
	// (POST /v1/apps/{id}/rollback)
	RollbackApp(w http.ResponseWriter, r *http.Request, id AppID, params RollbackAppParams)
	// Get cgroup resource stats
	// (GET /v1/apps/{id}/stats)
	GetAppStats(w http.ResponseWriter, r *http.Request, id AppID)
	// Fetch the daemon's public host key
	// (GET /v1/hostkey)
	GetHostkey(w http.ResponseWriter, r *http.Request)
	// List all registered volumes
	// (GET /v1/volumes)
	ListVolumes(w http.ResponseWriter, r *http.Request)
	// Register a persistent volume
	// (POST /v1/volumes)
	RegisterVolume(w http.ResponseWriter, r *http.Request)
	// Delete a volume
	// (DELETE /v1/volumes/{id})
	DeleteVolume(w http.ResponseWriter, r *http.Request, id VolumeID, params DeleteVolumeParams)
	// Get volume details
	// (GET /v1/volumes/{id})
	GetVolume(w http.ResponseWriter, r *http.Request, id VolumeID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListApps operation middleware
func (siw *ServerInterfaceWrapper) ListApps(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListApps(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SpawnApp operation middleware
func (siw *ServerInterfaceWrapper) SpawnApp(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SpawnApp(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StopApp operation middleware
func (siw *ServerInterfaceWrapper) StopApp(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AppID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params StopAppParams

	headers := r.Header

	// ------------- Optional header parameter "If-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-Match")]; found {
		var IfMatch string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "If-Match", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-Match", valueList[0], &IfMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "If-Match", Err: err})
			return
		}

		params.IfMatch = &IfMatch

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StopApp(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApp operation middleware
func (siw *ServerInterfaceWrapper) GetApp(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AppID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApp(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeployApp operation middleware
func (siw *ServerInterfaceWrapper) DeployApp(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AppID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params DeployAppParams

	headers := r.Header

	// ------------- Optional header parameter "If-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-Match")]; found {
		var IfMatch string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "If-Match", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-Match", valueList[0], &IfMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "If-Match", Err: err})
			return
		}

		params.IfMatch = &IfMatch

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeployApp(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAppEvents operation middleware
func (siw *ServerInterfaceWrapper) GetAppEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AppID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAppEvents(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAppLogs operation middleware
func (siw *ServerInterfaceWrapper) GetAppLogs(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AppID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAppLogsParams

	// ------------- Optional query parameter "tail" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tail", r.URL.Query(), &params.Tail, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "tail"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tail", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "follow" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "follow", r.URL.Query(), &params.Follow, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "follow"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "follow", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAppLogs(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResetApp operation middleware
func (siw *ServerInterfaceWrapper) ResetApp(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AppID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResetApp(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RestartApp operation middleware
func (siw *ServerInterfaceWrapper) RestartApp(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AppID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RestartApp(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RollbackApp operation middleware
func (siw *ServerInterfaceWrapper) RollbackApp(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AppID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params RollbackAppParams

	// ------------- Required query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	headers := r.Header

	// ------------- Optional header parameter "If-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-Match")]; found {
		var IfMatch string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "If-Match", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-Match", valueList[0], &IfMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "If-Match", Err: err})
			return
		}

		params.IfMatch = &IfMatch

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RollbackApp(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAppStats operation middleware
func (siw *ServerInterfaceWrapper) GetAppStats(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AppID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAppStats(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHostkey operation middleware
func (siw *ServerInterfaceWrapper) GetHostkey(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHostkey(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListVolumes operation middleware
func (siw *ServerInterfaceWrapper) ListVolumes(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListVolumes(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterVolume operation middleware
func (siw *ServerInterfaceWrapper) RegisterVolume(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterVolume(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteVolume operation middleware
func (siw *ServerInterfaceWrapper) DeleteVolume(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id VolumeID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteVolumeParams

	// ------------- Optional query parameter "force" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "force", r.URL.Query(), &params.Force, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "force"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "force", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteVolume(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVolume operation middleware
func (siw *ServerInterfaceWrapper) GetVolume(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id VolumeID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVolume(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/apps", wrapper.ListApps)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/apps", wrapper.SpawnApp)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/v1/apps/{id}", wrapper.StopApp)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/apps/{id}", wrapper.GetApp)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/apps/{id}/deploy", wrapper.DeployApp)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/apps/{id}/events", wrapper.GetAppEvents)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/apps/{id}/logs", wrapper.GetAppLogs)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/apps/{id}/reset", wrapper.ResetApp)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/apps/{id}/restart", wrapper.RestartApp)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/apps/{id}/rollback", wrapper.RollbackApp)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/apps/{id}/stats", wrapper.GetAppStats)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/hostkey", wrapper.GetHostkey)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/volumes", wrapper.ListVolumes)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/volumes", wrapper.RegisterVolume)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/v1/volumes/{id}", wrapper.DeleteVolume)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/volumes/{id}", wrapper.GetVolume)

	return m
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"3Hzrchs3lvCrnOpMVaQvTUryJRPLlR+yJCeqWI5LkjM1lfZHgd2HJEZoAAbQlDlZVe2vfYCtfYd9j32U",
	"eZItXLrZTYIXO5aczS+JJBo49xvO6d+SXJRScORGJ4e/JZIoUqJB5T4dSXl2Yv8pUOeKSkMFTw7t10AL",
	"5IaOKCrYOXl92WNkiAxGQpXE7CZpQu1CScwkSRNOSkwOE1okaaLwfUUVFsmhURWmic4nWBJ7Rkk+vEI+",
	"NpPk8NvHaVJSXn98lNqdDCq75///lfT+ud979i787b37f/U3f0nSxMykPUsbRfk4ubtLk18Eq0qM4eF/",
	"aaHySXAvnnhnF2spuEZHxBekuMD3FWpjP+WCG+TuXyIlozmxwOz9Q1uIfmtt+xeFo+Qw+WpvzqA9/6ve",
	"O1VKqItwiD+yi9kZnxJGC1Dh4Ls0eS3MS1Hx4uGAuEAtKpUjcGFg5M6+S5M3CnPBC2oXvSSU4QNCdDbq",
	"nROTT2CCpEAFBS0ccKX70kwQ8kop5AZUgP0XVJoK3s94vS8MRTEDynNWFajXPQRaQM6oBTHjOeGg0KhZ",
	"H15SpU1PEmVm9e9w+ePPb1+dgEZeQAOl4BnXEvNeWRliKB9DThjTz6GkWtuPAQ2qgTAmbrGAYWUAS2o0",
	"kIxf/40oTvn4EB49ewY9yJKKN7QnrHerqMEsuYZaXsOG/YwnaeL/dyJ8ekXGy+pzvALtHSHJ+wrBa8Qu",
	"iJGjUr2sn6zVnrs0ectJZSZC0X8+pHCcB6IKBTSozxCJQgVG3CB3tiRsFmzjMkl++k73tJmxObaAfIpM",
	"SOzDJSKcnF6e/fC6p5GNehOhTU8bYrBfFhnPkqsJAuUGlZA9e7SFRldDjSZLrGl1ZBxRZAVoLAk3NNee",
	"V1IJicpQb3GIpIEX9hPyqkwOf01yhXjTL3C6Nz0gTE7IQfJuyV6myQ31NqJ+zOIZW1eiIQUxG+l+JOV5",
	"vdRSUGK+xSOXdpldboip9DYP+IXe+tam+tc2KQJqLcgDNM0pczTF8B+YO7N5JOXpNAjfIpXlgBYRGXaq",
	"w8xkMCKUVcqv9p7RehNuvn0yd1SW32NU9inZ2a39g1Am/otCbYgyg1xUfMWSOQWXwDRdyApisGdoiUmE",
	"3f6LDSpmCXVlF96lSaVYTL+77HG/pjUpHUQrmHDeErcuH3KFzh5c0dJSo4yo5cXL48ePHz/rw1lpTemQ",
	"4XOQCjWqKRZAciW0thprhHLmaTuSjJGjIiaoWffEF1UpNQgOOEU1A13lOWo9qhhYkQNnefvw+ucrGFal",
	"xMIu9ZxKgXAujNtXp9YaudBKd+CqhaiknJZWT/djAuXjl0XQfqxKwnsKSWEJAWcnKTShFBz0vn0M+YQo",
	"d94Sygumfnnzn73pPz669FazD8fBw52/vbxyCBcCiKJmUqKhucWbmuhZlVeH7v5v356dTP/ah0vHxTnr",
	"LKrPgVtqg8JKY9GhV1V58VorjI5c/twOc5fRTiNCt0JuL4O966JxgtqeCt76wyUaj8+wiQj6y1Zdjd1f",
	"arBcoc/+C6IUmdnPuShLwuMmCvn04zZbY4Qq7lQkqu1RmjQmaUF4hkEjG7KoKSoXphjkz5tgSWGOdIrw",
	"ZP+plR+nTBGCNaFO5KhjJrQ9CI0NT0R9cPMIWLj1IVwgKWYpvFFirNDFB2nGT3CsSIFFCi9IflNJt6gP",
	"F2htYmWsSTHww+kVWLLASIkSdCVRTakWKuOBXjWW1utbOKiGEf2ABVAOtYeGf/37fwEpChsJEOB4m/Eu",
	"iBAEWAPhcHRy4cOBhqvrrPVxvVFUdHxs92aVS6p/XykU3gW+/DgPyNGcyag01hz6YY3NfUW08eZ1rrwu",
	"ZCpQMjGDERO3MCHacnmKaowFGAEEPKgzzw8QPGppV/re49Wut5KWz+fbYb9gjCIIp22J7rCoy48F0JZ4",
	"0QJshdH6heJtJOD5sgbo04KqFREaRzOgcVG7nzCsZSTXKeVFWNYJ3OpQvOI3XNxyH7AqmxAmbmPu/8sV",
	"0RMs6v96TAjpf9FGSOl+qXiQ9mhM7+ViUH6SxHo5DBwP1Gqw8GRtn7BItWUGx4RzbrSW1N97FWfOOYJ1",
	"5gXUprZRnD6cU5sI+sT9p+90x6BWkuEhEMi9d3AGdipyMqwYUbMUjKI+YQuxWsZ3rlSFsAcvCdP271vP",
	"ol0bxRXuDFNHCHUezIg2GW9cjlGE6wDbtUKiBb92GT0ckxLZMdHoQymbAWa8JPmEcoeRrkqH+3O4LlFr",
	"Mkb34KQT38XyQwvBVXPsVRDL7YLecFJUczz00Z+WhdkSLkkTR7jE5vxett+tyT3qR52/TdKk5ZWTNKm9",
	"cpImLbcc2TCegzSCGqFOg1pMJE+cd2mV+O7Xaho1+zz2dKxIjqOKDaYH22p8o6P5BPObgSuTxo5itKRm",
	"YwDyyq+qrbEWrHHsYcehEAwJ98aXsYErjkwJ2x7e2maX5INPlL59+vTx01bidBB37aSYDawKiMpsf9gn",
	"2HjCi6H4sOmJy7DsLk2mrmY9KK3N7MrVug18pfvcGdolUVjQB0eymKC7CtqxKDq6OCTFoK4yW/fSqtyl",
	"CRdm4Au/LnYZMZrbVYR5As9dlz1z0FoRCnC+KFB/qMmbJj6gG8yd2TxFG0x9jjYoqXZlXQeVrqQ9AovB",
	"iDLUM22w9H5RkTEOcqFUJQ36Qj9DonFgHeyI5GYgVcXRw2FQccKiNqpbXlwuUgSybaxQOvpadbYfNhdQ",
	"3L716ijTmppMi2ne1g3yCeHjgLS3qF0XPPfRSZoIUQ5uKItj/6PQ5gZnZ3wklh3zm2rIaA5YPHr69OAZ",
	"TIQ2cIMz+AZGlI9RSUW56cMRGwtXFwglTqozTqzTuyWq6Fl6EQOaCfMcBGczyJKwY5ZYt6cwF2NOnd8W",
	"BZlFC6P1EW1ihF2ieLUAXMZLT8ijp98eZtX+/uN8gh/cP1i7eemxtogOZyE/XY413aKfcLa8+5Bo/PZJ",
	"vdvjRz27S0PE+e79jXWNOdbtA7vIxUTnVWPFF2RZVgOJiopiUG1rGu0z7ythyPaPlFgKNRtM6HgycBT8",
	"uOdK8uGjHpO00PahbUPfCLm0OZJSrzYCRMrtTXadhm0y127Tdyvg8XZ/DUjenXysI9kKsHrrGGwX3shG",
	"SkAcwcU4QDkQDkTKr61uu+XAsBij6sOxQmJ80dTVVzPeKrCGbP8bUIKxIclvWmVfwA85SuMuU67lhGi8",
	"TjN+O6H5pBWIazjKDZ0i/Os//hMuK4lKY4EF/BtcCMawsOElEA0cb1FlPECngRFe+DKQKjQQhXBjD6O8",
	"wBHl1CCbBdtlJpjxiheo2MzVdoKzAVqSMfpnfzj+uoCdNxZIOOg/3Y0ZtGjte7tA3mHfuehxOCdpMsc4",
	"SZM5xlEDuc11TmB2faWzpq5r0yrLJX8jb2YfX8P1azxusSptgHiNTMYLtnMJkmTGBCnqPDM8ZXO3hlIv",
	"lSiv4ZuMXwtFx5QTdhT4G1Zfg8IRKuQ5OusergprMR/OMl5Dg+/hlpoJ9ZUsTUq0OvEc/olKwB5UXKOB",
	"EgnXkCUjhXqSca8BqbvaJo0aZEn8rlC+9QzZQOhATSxeRJzVWWBY7a5ywhgqMBNiIDwGZkIbTY46Q+TT",
	"H4mebO9op6hAu7AOfjr9+/dTwip33wqS0BUXGGNqLickmrQ41YsXH+NcXAbU3+wTKZEoYpnb4mKgTETp",
	"rcnQgk1RN7zq5RNiDWA5pONqURHWlSTr4yJRGCoLGZSCCyM4zcHVXVCtuTZZc1JH2KP6ggV1lRIv2y1K",
	"0FFHFuCW6EZIhrOWxG4Fy7I7fEtbcbylRVzbXWC7Mm3/yOQvFhBczNPBJluquEuLCp/FcBE1qpfzrHDB",
	"3E+UECYuvTIfcFKiliTHeArtcsZNi7gYcLwdSEWnekUmTotNm1Qa1cY1Rq9fEiPppSS3/I9Sallo/Tj9",
	"+/e/HL16e+qtT/sWZtvS9oaqijfT99Imd08lm0+qvfwpiii0KYHHjM+lIUbHL1nysRKVHCC3wUYRJ6xN",
	"pipNxjiotA9WPv0iJGRL4f7oIRKtupDwUYlZgG/bQhySYoBqi/qJv7To0jzGsTbvl3jmjrNxfZxduhqu",
	"VmpD1BjjJj1IaZRx0Vwr9ND4HVdjsdJ+Wp9L+XiTBYrV/VfjHyN456DVgMY1ZCOUIz2obwy+FAaW65hX",
	"iprZpbUeAXLXTnhUmUiMe3xxevrTyeDo5Pzs9eDq559OX9dtkg4W9+Rc1ifGSN/DSOMlNyVsOtxqOwBS",
	"lJTD0Zszl/y6ZsCin/EjxgB5IQX1nRUOT3jRanwEUpmJDe992yXcTpDDMrhANWg0Pscw1DALpz8Gjuqz",
	"kzSZ1q1DyX7/oL/vLIJETiRNDpPH/f3+48T5sYkj2d70YK8umwQ9sbLgIDkrksOm6pIsdF0/2t//bK2j",
	"S5WdSPeoXWNjfAfsXZo82T9YtW0D516n0dUJTVWWxEYdfj/CWMNCLPzeVsFtmFNXfpyj1RHKuFjpSMrQ",
	"vI7avBDF7LMRpROK3XWVxKgK75YYcvDZzm5qY8t8OJIStAUNi1bXHZt5nuxv5kmrXf/T2GgfevZwbcsW",
	"4XChAuFCBYQCG3tAc6PSlS3HOt9PtCBey9J1lzY6uPcbLe68rWFoIunvUZ6jNBqE9A3mcF23sh+CT94X",
	"Gul8In89bzs/D5c2rvL25OARtKcFwI8LuHrIvOd+CpRnXLW78/tw3m2Qt7t1Wt/Bo5C6vX5vo/yC2hkh",
	"vda1Z2l+/cjm+V2Hg6fFjCIrtCVHvx5Q8cfPR1RqOq9trX+3pJFP4rM9dbvIp8v/k80PNfMo9oGDR5sf",
	"iAyOLIi1EdK1XSgsxRRD+ThmMIMnWRxXMZXivjHEUqHp4A+1t5vvNNxShT0fgDaN/Rm//m3eZp7CDeVF",
	"CnWTeeo60tLQMHJ33YerCdXWWboa8IgqbRoHDEZApX1NsN4e9IRIfA61OYdvoPZHGdeGMgbKQe6bS3BM",
	"8hkEA+mfhaJyowTtXa3GjEhuhIKdW7sHs4STqHoTwguGKlTXqqG2xpAbeHOhd/sZXzvEAP/z3+unGGIK",
	"8wOa2kvdk/+226+wnDU9HkrWOwL7AxoroVCgIZRp2LlpxkdquHaj/r5rWGJnz5fs+SG+u3eLlnzPl4kX",
	"p/6233AeePwfdgO+Uv753YDvCvoDO4LPHxF2G6G2Cgn3HyIk9HCBfcg7fRv3hDQEGJ3iw8aGH+sbHzKY",
	"fNOOGm0YGS5T6wCTcpCh6e53+e00ebr/6OHQet1i+MhbD19yBVdyXTDLL1iFvbFC5A36bZHZHCPv4bSe",
	"p47mrN7jnfpFG3XC4Afjd+xpo5CUH6UUfngtQpMwXHFpbY8HBcL2X8IVXl6ehuNDEh268VuX8vfoCZkY",
	"b+LWK7tkgyl/XZVDGzmNgFGO2k9++KirqA32+wrVbG6vrePv2OoCR6RiJjk82N9P56Xzg/1993nNvNdd",
	"utwR7QhqZdcDRDRYQmMteTGIRoIxcduBqb69sjY81k/77vfKcGRsyD4gGaF8/colsf4bNRNRGfBoHMJ8",
	"Ix8w1B3Y8NrTpJ9x+0hY/71FMTzUBtc/Szk1lDCwTLMbee8BlSyIcTt9EdW5QOJyd2BiDKIysjL3qCoK",
	"tVeS3xszdpXswm57/2nAuqqRwyzkj+5u2LMmmiU7cH19yXUGDSsfyVMNXAATfIzKT5jyP2uocFSja6A7",
	"brIonY6q3TXblZr26ubT+5A2u/H9FUcXugvult8K8rCCPRfnL2Ce3OkrqzHLXA/dH58/Mb3AnqpChad1",
	"M9L4hWPBR3R8yYnUE2FA2nhPGzeRmXE3y+Ou1uY9X74PUYf4MHztOpFVATtuX5Jx15WVthpv5r0wu+Dq",
	"Pk4lDMyP+FpnvOkJnFKy3F1m7dTK9rJ+xq8mCFJRoepexrrbZsSo1GAEuCa571sdjTtcmIzPu/9SKKi2",
	"sFVUTyyINWd8YBM6s0OMvNvPeMavjbgOta0FYn2tW2j7odewoKy0yXhOlLKB9nXeYcK1m4C9qDssmzYh",
	"HAmF8NV3ecZ3hJpDRrkb6WxaiywLbLAgJRagw6a7oWKW8ScHj+B6Rcf/tcPoU4sZ87Q946GKESsTXATA",
	"tygUXHXoeYnvLRMt4uAwN6K/KsYUa99ftPqlAgfbBJl/iEL2/me03L63L/Y+o1rIupWEWu2J7599+FrC",
	"w/l7oWqlrRWsebVTH/5mA2L/oh//mxvgGNoQCH6+cIPXXEClXRdt19Sm0Dm+n4sCM071Wt38fBcHFy0l",
	"AhLMZjh5C4dlM9VN6aPr+LnP4HbeUrTuTVwe1C9V6/Z9NvOLFR2I8nlzlYmfRWoxZPU9z/I4TXcqyXcw",
	"azrmOuNXFBXsO0GpJJSE0xFqo2Hnq7/uOn9sXZXgOcJXjw6grJih7noEjo8yLpUohStfM8IL7da6Jl/t",
	"fZZ7tRNDtKvDHVF9K+Q04e3ro7dXP56+vjo7Pro6PQEtQiorjZBfa7h2rRYuRYVejxRCmuuMu1ce7Lwh",
	"ZgIvdiEnHGS4zWojGbwp4bOM5wpdLzdhfgoBP4QpsT64bY5gJydSG8J7UokptbYei92Mj9HopZ1t6OKG",
	"oezSApXrP6FcGyTFc7/hsUPP64xQPUlcxCUq0xOj3tBNVGx4cZa7dPr55VsInLdhSy7cXEjifPhVdxyL",
	"6vrTcAZhNMMyxrIEP0jhrgyoyfhtqCVYLbBP5UIpzE0fjjgQY0h+gwpuJ8IR9vzs6tz1NbduIez3uhpq",
	"Q01l3LUeVSBuuQXjuSNMjbd7PU7Gp6joaAZkbAXDxcwtQrSGBnYaguaCa8EwtRGUZ4sPP7FoM8K9R0gS",
	"iQqGFS8Y7gamZ1xS1zOw4mYuDPbdp+Vqzw5GbNeP9big63RylePHD+f1mtOto5uhqWtArmFiB4lis95Q",
	"CFcr5yIULQvq+DKi40phsdtpB0sOf33XtosvsX71YEGwFPzrRjjrOcmWgaznYuZeqDW/tbI9KgyB3XeH",
	"1OKs2ZomqRrqz9knpXBskzWFRbP9nHDNLNrd6pKAf9xjcU9lgW7/5QM3TbVH95ZZE96FOqfin7ZhKmBa",
	"X2nhB6qNXipaeDLYaDBUAaw3q2VjWay66hjplFq8HbbfN7K2Nu97KWys5HdypXugvs2wM0RG9Ry8eFlf",
	"5RjLquZtrlv1BwXqeXCKP2lts34xMHfdOMN5Y53v7uyIimclkHXSka5MDVrm5p5M81ZqHzpQvlhmMO2C",
	"scJwf1RW0Lz2+e7dgv/tNmL/+s4KvnsZT1T9TvyFHDCRExa6qElRuCvw8JZL1459uLfnlli3ffhs/7t9",
	"V4gMeES67Gp2AqMjzGc5Q5tSkDGW6N6GFPQ29BNHpvm6Vin68NzP/haLa+pwAnZc+GxTgyZ03m2//zpE",
	"HXfv7v43AAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
