//go:build go1.22

// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package apitypes

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all supervised apps
	// (GET /v1/apps)
	ListApps(w http.ResponseWriter, r *http.Request)
	// Spawn a new supervised app
	// (POST /v1/apps)
	SpawnApp(w http.ResponseWriter, r *http.Request)
	// Stop and remove an app
	// (DELETE /v1/apps/{id})
	StopApp(w http.ResponseWriter, r *http.Request, id AppID, params StopAppParams)
	// Get app details (k8s-style envelope)
	// (GET /v1/apps/{id})
	GetApp(w http.ResponseWriter, r *http.Request, id AppID)
	// Blue-green deploy a new version
	// (POST /v1/apps/{id}/deploy)
	DeployApp(w http.ResponseWriter, r *http.Request, id AppID, params DeployAppParams)
	// SSE stream of app state transitions
	// (GET /v1/apps/{id}/events)
	GetAppEvents(w http.ResponseWriter, r *http.Request, id AppID)
	// Read app log output
	// (GET /v1/apps/{id}/logs)
	GetAppLogs(w http.ResponseWriter, r *http.Request, id AppID, params GetAppLogsParams)
	// Reset a crash-looping app
	// (POST /v1/apps/{id}/reset)
	ResetApp(w http.ResponseWriter, r *http.Request, id AppID)
	// Restart an app
	// (POST /v1/apps/{id}/restart)
	RestartApp(w http.ResponseWriter, r *http.Request, id AppID)
	// Get cgroup resource stats
	// (GET /v1/apps/{id}/stats)
	GetAppStats(w http.ResponseWriter, r *http.Request, id AppID)
	// List all registered volumes
	// (GET /v1/volumes)
	ListVolumes(w http.ResponseWriter, r *http.Request)
	// Register a persistent volume
	// (POST /v1/volumes)
	RegisterVolume(w http.ResponseWriter, r *http.Request)
	// Delete a volume
	// (DELETE /v1/volumes/{id})
	DeleteVolume(w http.ResponseWriter, r *http.Request, id VolumeID, params DeleteVolumeParams)
	// Get volume details
	// (GET /v1/volumes/{id})
	GetVolume(w http.ResponseWriter, r *http.Request, id VolumeID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListApps operation middleware
func (siw *ServerInterfaceWrapper) ListApps(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListApps(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SpawnApp operation middleware
func (siw *ServerInterfaceWrapper) SpawnApp(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SpawnApp(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StopApp operation middleware
func (siw *ServerInterfaceWrapper) StopApp(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AppID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params StopAppParams

	headers := r.Header

	// ------------- Optional header parameter "If-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-Match")]; found {
		var IfMatch string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "If-Match", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-Match", valueList[0], &IfMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "If-Match", Err: err})
			return
		}

		params.IfMatch = &IfMatch

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StopApp(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApp operation middleware
func (siw *ServerInterfaceWrapper) GetApp(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AppID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApp(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeployApp operation middleware
func (siw *ServerInterfaceWrapper) DeployApp(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AppID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params DeployAppParams

	headers := r.Header

	// ------------- Optional header parameter "If-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-Match")]; found {
		var IfMatch string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "If-Match", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-Match", valueList[0], &IfMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "If-Match", Err: err})
			return
		}

		params.IfMatch = &IfMatch

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeployApp(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAppEvents operation middleware
func (siw *ServerInterfaceWrapper) GetAppEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AppID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAppEvents(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAppLogs operation middleware
func (siw *ServerInterfaceWrapper) GetAppLogs(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AppID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAppLogsParams

	// ------------- Optional query parameter "tail" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tail", r.URL.Query(), &params.Tail, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "tail"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tail", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "follow" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "follow", r.URL.Query(), &params.Follow, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "follow"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "follow", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAppLogs(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResetApp operation middleware
func (siw *ServerInterfaceWrapper) ResetApp(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AppID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResetApp(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RestartApp operation middleware
func (siw *ServerInterfaceWrapper) RestartApp(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AppID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RestartApp(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAppStats operation middleware
func (siw *ServerInterfaceWrapper) GetAppStats(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AppID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAppStats(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListVolumes operation middleware
func (siw *ServerInterfaceWrapper) ListVolumes(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListVolumes(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterVolume operation middleware
func (siw *ServerInterfaceWrapper) RegisterVolume(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterVolume(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteVolume operation middleware
func (siw *ServerInterfaceWrapper) DeleteVolume(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id VolumeID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteVolumeParams

	// ------------- Optional query parameter "force" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "force", r.URL.Query(), &params.Force, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "force"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "force", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteVolume(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVolume operation middleware
func (siw *ServerInterfaceWrapper) GetVolume(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id VolumeID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVolume(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/apps", wrapper.ListApps)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/apps", wrapper.SpawnApp)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/v1/apps/{id}", wrapper.StopApp)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/apps/{id}", wrapper.GetApp)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/apps/{id}/deploy", wrapper.DeployApp)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/apps/{id}/events", wrapper.GetAppEvents)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/apps/{id}/logs", wrapper.GetAppLogs)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/apps/{id}/reset", wrapper.ResetApp)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/apps/{id}/restart", wrapper.RestartApp)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/apps/{id}/stats", wrapper.GetAppStats)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/volumes", wrapper.ListVolumes)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/volumes", wrapper.RegisterVolume)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/v1/volumes/{id}", wrapper.DeleteVolume)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/volumes/{id}", wrapper.GetVolume)

	return m
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"3Fzrchu5cn6Vrsn5sU6GFOXLZi3X+SFLso9qLa1LkvdUylQocKZJ4ggDwACGMo+LVfmVB0jlHfIeeZTz",
	"JClcZjhDghd5LXmzv8Th4NLoy9eN7qa+JJkopODIjU4OviSSKFKgQeWeDqU8PbYfctSZotJQwZMD+zXQ",
	"HLmhI4oKfjg+v+wwMkQGI6EKYp4kaULtQEnMJEkTTgpMDhKaJ2mi8FNJFebJgVElponOJlgQu0dBPr9D",
	"PjaT5ODHZ2lSUF49Pk3tSgaVXfPfP5LO33udl9fhb+f6n6tv/pSkiZlJu5c2ivJxMp+nya+ClQXGzuHf",
	"NI7yVXQv7zi3g7UUXKNj4muSX+CnErWxT5ngBrn7SKRkNCOWmL2/aUvRl8ayf1I4Sg6Sf9pbCGjPv9V7",
	"J0oJdRE28Vu2T3bKp4TRHFTYeJ4m58K8ESXPH4+IC9SiVBkCFwZGbu95mrxXmAmeUzvoDaEMH5Gi01Hn",
	"jJhsAhMkOSrIae6IK9yXZoKQlUohN6AC7b+i0lTwbp9X68JQ5DOgPGNljnrTJNACMkYtiX2eEQ4KjZp1",
	"4Q1V2nQkUWZWvYfLv/zy4d0xaOQ51FQK3udaYtYpSkMM5WPICGP6FRRUa/sYjkE1EMbEHeYwLA1gQY0G",
	"0uc3fyWKUz4+gKcvX0IH+knJa94T1rlT1GA/uYFKX8OC3T5P0sR/dip8ckXGq+ZztObYPwhJPpUI3iKe",
	"gBg5LlXDuslG65mnyQdOSjMRiv79MZXjLDBVKKDBfIZIFCow4ha5w5KwWMDGVZb8/JPuaDNji9MC8iky",
	"IbELl4hwfHJ5+va8o5GNOhOhTUcbYrBb5H3eT64mCJQbVEJ27NaWGl0ONZp+YqHVsXFEkeWgsSDc0Ex7",
	"WUklJCpDPeIQSYMs7BPyskgOPiaZQrzt5jjdm+4TJidkP7lewcs0uaUeI6pp9pyxcQUakhOzle+HUp5V",
	"Qy0HJWY7TLm0w+xwQ0ypd5ngB3r0raD6Y5MV4WgNygM19S6LY4rh3zBzsHko5ck0KN8yl+WA5hEddqbD",
	"zGQwIpSVyo/2ntF6E25+fL5wVFbeY1R2lmyt1nwhlIm/UagNUWaQiZKvGbLg4AqZpk1ZTgx2DC0wiYjb",
	"f7HFxCyjruzAeZqUisXsuy0e9zatWOkoWiOEs4a6teWQKXR4cEULy40iYpYXb46ePXv2sgunhYXSIcNX",
	"IBVqVFPMgWRKaG0t1gjl4Gk3loyRoyImmFl7x9dlITUIDjhFNQNdZhlqPSoZWJUDh7xdOP/lCoZlITG3",
	"Q72kUiCcC+PW1alFIxda6RZdlRIVlNPC2mkvplA+flkm7S9lQXhHIcktI+D0OIU6lIL9zo/PIJsQ5fZb",
	"OfIS1K8u/ouH/qPDS4+aXTgKHu7sw+WVO3AugChqJgUamtlzUxPdq/Tm0F7/w4fT4+m/duHSSXEhOnvU",
	"V8Att0FhqTFv8assvXptVEbHLr9vS7irx04jSrdGby8D3rWPcYza7goe/eESjT/PsI4IuquorsbuLzVY",
	"rLFn/wVRiszscyaKgvA4RCGf3m+xDSBUcmciUWuP8qSGpCXlGQaLrNmipqhcmGKQv6qDJYUZ0inC894L",
	"qz/OmCIMq0OdyFZHTGi7ERobnohq43oKWLr1AVwgyWcpvFdirNDFB2mfH+NYkRzzFF6T7LaUblAXLtBi",
	"YmkspBh4e3IFli0wUqIAXUpUU6qF6vPAr+qU1utbOqiGEf2MOVAOlYeGf/zHfwPJcxsJEOB41+dtEiEo",
	"sAbC4fD4wocDtVQ3ofVRtVBUdXxs936dS6rer1UK7wLf3M8DcjSnMqqNlYTebsDcd0QbD68L43UhU46S",
	"iRmMmLiDCdFWylNUY8zBCCDgSZ15eYDgUaRd63uP1rveUlo5n+12+iUwihw4bWp0S0RteSyRtiKLBmFr",
	"QOtXineRgOf7AtDXBVVrIjSOZkDjqvYwYVgDJDcZ5UUY1grcqlC85Ldc3HEfsCp7IUzcwtx/yhTRE8yr",
	"Tx0mhPRvtBFSujclD9oejem9XgyKr9JYr4dB4oFb9Sk8W5s7LHNtVcAx5VyA1or5e6/i4JwjWGeeQwW1",
	"teF04Yzai6C/uP/8k24BaikZHgCBzHsHB7BTkZFhyYiapWAU9Re2EKv1+Q9XqkTYgzeEafv3gxfRExvF",
	"5W4PU0UI1T2YEW36vHY5RhGuA203CokW/Mbd6OGIFMiOiEYfStkbYJ8XJJtQ7k6ky8Kd/RXcFKg1GaOb",
	"OGnFd7H7oaXgqt72KqjlbkFv2ClqOZ766KtVZbaMS9LEMS6xd36v29cb7h7VVOdvkzRpeOUkTSqvnKRJ",
	"wy1HFozfQWpFjXCnPlpMJY+dd2mk+B4WNY2afRs8HSuS4ahkg+n+rhZf22g2wex24NKksa0YLajZGoC8",
	"86MqNNaC1Y49rDgUgiHhHnwZG7jkyJSw3emtMLsgn/1F6ccXL569aFyc9uOuneSzgTUBUZrdN/sKjCc8",
	"H4rP22ZchmHzNJm6nPWgsJjZ1qtNC/hM95kD2hVVWLIHx7KYorsM2pHIW7Y4JPmgyjJb99LI3KUJF2bg",
	"E78udhkxmtlRhHkGL1yX3XPQGBEScD4pUD1U7E0TH9ANFs5scUUbTP0dbVBQ7dK6jipdSrsF5oMRZahn",
	"2mDh/aIiYxxkQqlSGvS7GVScsCgStZOIq6mIwJyteUjHRWu09mF7msStW42OiqbOvDRE4xFtkE0IH6Ov",
	"YXjcbDvahSdO0kSIYnBLWfz072qzXjq2LAcSFRX5oNzVVuycT6UwZPcpBRZCzQYTOp4MhjOD95xXkM/3",
	"miZpru2kXWOhFaG8o9ocSqnX6wuRcncbruLybfbrFr1eQ48Hgg0keXy5L7LsRFi1dIy2C6+Ba73oPbE4",
	"Jo6LBTrX4FVyh1K5BxUuomp/uQDpJb2fKCFM1ANSmQ1sCKolyTDu0RyEbxvExYDj3UAqOtVrHCPNty1S",
	"alRbxxi9eUiMpZeS3PHfS+SzVIk5+bc//3r47sMJSEKVbiZFdr1pbgly/DXxQarWDxRBfVUo9IeIaWh9",
	"I42Bj7056njOIxsrUcoBcnuXyuOMta6stJeiQal9svfr8xLBV4V0zmO4ucrj38stBvp2jYuR5ANUOwQ6",
	"PofQ5nlMYk3Zr8jMbSc4m8XFpcvheqM2RI0xDulBS6OCi3q6UNLyK64/xVr8HJLslvLxNgSKXcPXnz/G",
	"8NZG6wmNW8hWKkd6UF3gv9cJrNQxKxU1s0uLHoFyV90/LD3dS/WBi5OTn48Hh8dnp+eDq19+PjmvuhYc",
	"LW7mQtcnxkjfUkD5SKyu9l6JDLVuVAGA5AXlcPj+1BX2XW0+7/b5IWOAPJeC+kKHOye8bvQhgL1hITeh",
	"CwLuJshhlVygGjQan/4x1DBLp98GDqu9kzSZVpW8pNfd7/YcIkjkRNLkIHnW7XWfJc6PTRzL9qb7e1XQ",
	"GuzE6oKj5DRPDuqYN1lqgnra632zTo6VuDrSzGHHgBiBI3aeJs97++uWrenca/WdOKUpi4LYqMOvRxir",
	"RYi5X9sauA1zqrjbOVod4YyLlQ6lDL1kqM1rkc++GVNaodi8bSRGlThfEcj+N9u7vpmsyuFQStCWNMwb",
	"RXA28zLpbZdJo3vu68RoJ718vC4ie+CQ34CQ3wChwMYeUCc42rrlROfLe0vqtapd87S2wb0vNJ97rGFo",
	"IoX+wyxDaTQI6fu94KbqLDuAftnrPcuW6truS7xZdIGdhRwK/OM//wue7z+FZvMe+O49uKNmsmiBmwLl",
	"fa6azXJdOGv3q9nVWp1o4I+QurV+a9/aktkZIb3VNVtbP96zl+2JO4PnxYwiy7VlR7fqF/XbLzpGKz5v",
	"7HS7XrHI5/FW26p68/X6/3z7pLo91E7Yf7p9QqSPc0mtjZCuCqKwEFMEwuMqnVaeZLl71JSK+zqN5ULd",
	"UEd9Uff2Jw13VGHHB6B1n12f33xZdH2lcEt5nkLV85W6AnEa6jfzmy5cTai2ztJMsM9HVGlTO2AwAkqN",
	"brtqedATIvEVVHAO/wKVP+pzbShjoBzlvtaDY5LNIACknwt56Tr7mqtaixmRzAgFP9zZNZhlnETVmRCe",
	"M1Qgpqh8M+Cn0irq+wv9pNvnG3sK4X//Z3NTYcxg3qKpvNQD+W+7/BrkrPjxWLreUti3aKyGQo6GUKbh",
	"h9u6m7Oi60nU37eBJbb3Ysie76mfXy8j+Z5Pai834e++4CLw+H/sBiwLHsIN+CLd79gRfPuIsF2X3Ckk",
	"7D1GSOjpAjvJO30b94RrCDA6xceNDe/rGx8zmHzfjBptGBk6maoAk3KQoQb+m/x2mrzoPX28Y503BD7y",
	"6OFTruBSrkuw/JqV2BkrRF4fv6ky22PkPZxWP2+K3lm9xzvxg7bahMHPxq/Y0UYhKe5lFL6XPMKT0Ot4",
	"abHHkwJh+e/hCi8vT8L24RIdmuMWzSr6AT0hE+Nt0npnh2yB8vOyGNrIaQSMctS+EdNHXXkF2J9KVLMF",
	"XlvH38LqHEekZCY52O/10kXqfL/Xc88b2q/n6WqDkmOo1V1PENFgGY2V5sUoGgnGxF2Lpqp6ZTE81t5y",
	"/Vt1ONLFaydIRijfPHJFrf9KzUSUBvwxDmCxkA8YqoYoOPc86fa5nRLG/9keMUxqkuvnUk4NJQys0OxC",
	"3ntAKXNi3ErfxXQukLi7OzAxBlEaWZoHNBWF2hvJb40Z20Z2YZd9+GvApqyRO1m4P7rasBdN9JbsyPX5",
	"JczDr+CsCKgGLoAJPkblf/DB/6ihwmF1XAPt7s9l7XRcbY/ZLdW0V3WJPIS22YUfLjm61F0wX/2R7uMq",
	"9kKdvwM8ud3XZmNWpG4d/zZv7AqoD4kViwrtpt8Ze1K/V+rAly0XeSodmPJtob/Rn7O2ABOafB66BrPc",
	"S7ShDFNR/S0rMQrHVBtUmNfLL5hd9xrN14OOn+5P8UDA067wPnJZptmatSqa8M8PFlz8w5ZkwkmrSzN+",
	"ptroFVj0bAAC0t4rtaUr6FVUrdrmGKnFLOef7Pe1rm28t7wRFj78Su5yANQXMkHhCBXyDMFMqF6QF784",
	"qAxjeadFIX2nCkTgnicn/4NGT9V/AuEu3z9clO58/bilKl6UQDZpR7rWWzbg5oGgeSezDznu7+Ysp20y",
	"1gD3vRxl/X9e5tfNhg83tdnq8fHaKr779U3U/I79lR+YyAgLfRokz12SLfys3TV8HOztuSEToc3By95P",
	"PRfhhnNE6niVOIHREWazjCEUhJMxFuh+/hTsNnQsrLSQLKNSdHLtZ6/n/xcAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
