// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package apitypes

import (
	"time"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for AppViewStatus.
const (
	CrashLoop AppViewStatus = "crash_loop"
	Running   AppViewStatus = "running"
	Starting  AppViewStatus = "starting"
	Stopped   AppViewStatus = "stopped"
	Stopping  AppViewStatus = "stopping"
)

// Valid indicates whether the value is a known member of the AppViewStatus enum.
func (e AppViewStatus) Valid() bool {
	switch e {
	case CrashLoop:
		return true
	case Running:
		return true
	case Starting:
		return true
	case Stopped:
		return true
	case Stopping:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	ErrorCodeAlreadyRunning  ErrorCode = "already_running"
	ErrorCodeBadRequest      ErrorCode = "bad_request"
	ErrorCodeConflict        ErrorCode = "conflict"
	ErrorCodeDeployUnhealthy ErrorCode = "deploy_unhealthy"
	ErrorCodeInternal        ErrorCode = "internal"
	ErrorCodeInvalidId       ErrorCode = "invalid_id"
	ErrorCodeInvalidRuntime  ErrorCode = "invalid_runtime"
	ErrorCodeNotFound        ErrorCode = "not_found"
	ErrorCodePortConflict    ErrorCode = "port_conflict"
	ErrorCodeUnauthorized    ErrorCode = "unauthorized"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case ErrorCodeAlreadyRunning:
		return true
	case ErrorCodeBadRequest:
		return true
	case ErrorCodeConflict:
		return true
	case ErrorCodeDeployUnhealthy:
		return true
	case ErrorCodeInternal:
		return true
	case ErrorCodeInvalidId:
		return true
	case ErrorCodeInvalidRuntime:
		return true
	case ErrorCodeNotFound:
		return true
	case ErrorCodePortConflict:
		return true
	case ErrorCodeUnauthorized:
		return true
	default:
		return false
	}
}

// Defines values for EventType.
const (
	HealthFailure EventType = "health_failure"
	OomKill       EventType = "oom_kill"
	Ready         EventType = "ready"
	Restart       EventType = "restart"
	StatusChanged EventType = "status_changed"
)

// Valid indicates whether the value is a known member of the EventType enum.
func (e EventType) Valid() bool {
	switch e {
	case HealthFailure:
		return true
	case OomKill:
		return true
	case Ready:
		return true
	case Restart:
		return true
	case StatusChanged:
		return true
	default:
		return false
	}
}

// Defines values for Runtime.
const (
	Bun  Runtime = "bun"
	Deno Runtime = "deno"
	Node Runtime = "node"
)

// Valid indicates whether the value is a known member of the Runtime enum.
func (e Runtime) Valid() bool {
	switch e {
	case Bun:
		return true
	case Deno:
		return true
	case Node:
		return true
	default:
		return false
	}
}

// Defines values for GetAppLogsParamsFollow.
const (
	GetAppLogsParamsFollowTrue GetAppLogsParamsFollow = "true"
)

// Valid indicates whether the value is a known member of the GetAppLogsParamsFollow enum.
func (e GetAppLogsParamsFollow) Valid() bool {
	switch e {
	case GetAppLogsParamsFollowTrue:
		return true
	default:
		return false
	}
}

// Defines values for DeleteVolumeParamsForce.
const (
	DeleteVolumeParamsForceTrue DeleteVolumeParamsForce = "true"
)

// Valid indicates whether the value is a known member of the DeleteVolumeParamsForce enum.
func (e DeleteVolumeParamsForce) Valid() bool {
	switch e {
	case DeleteVolumeParamsForceTrue:
		return true
	default:
		return false
	}
}

// AppEvent defines model for AppEvent.
type AppEvent struct {
	AppId          string    `json:"app_id"`
	HealthFailures *int64    `json:"health_failures,omitempty"`
	Pid            *int      `json:"pid,omitempty"`
	Port           *int      `json:"port,omitempty"`
	RestartCount   *int      `json:"restart_count,omitempty"`
	Status         *string   `json:"status,omitempty"`
	Ts             time.Time `json:"ts"`
	Type           EventType `json:"type"`
	Url            *string   `json:"url,omitempty"`
}

// AppView defines model for AppView.
type AppView struct {
	Args           *[]string     `json:"args,omitempty"`
	Command        string        `json:"command"`
	Env            *[]string     `json:"env,omitempty"`
	HealthFailures int64         `json:"health_failures"`
	Id             string        `json:"id"`
	NetIp          *string       `json:"net_ip,omitempty"`
	Pid            int           `json:"pid"`
	Port           int           `json:"port"`
	RestartCount   int           `json:"restart_count"`
	Runtime        *string       `json:"runtime,omitempty"`
	Status         AppViewStatus `json:"status"`
	UptimeMs       int64         `json:"uptime_ms"`
}

// AppViewStatus defines model for AppView.Status.
type AppViewStatus string

// DeployRequest defines model for DeployRequest.
type DeployRequest struct {
	Args            *[]string      `json:"args,omitempty"`
	Command         *string        `json:"command,omitempty"`
	Entry           *string        `json:"entry,omitempty"`
	Env             *[]string      `json:"env,omitempty"`
	GracefulV1Ms    *int64         `json:"graceful_v1_ms,omitempty"`
	HealthCheckPath *string        `json:"health_check_path,omitempty"`
	Limits          *Limits        `json:"limits,omitempty"`
	NetIsolation    *bool          `json:"net_isolation,omitempty"`
	PollIntervalMs  *int64         `json:"poll_interval_ms,omitempty"`
	Port            int            `json:"port"`
	ReadyTimeoutMs  *int64         `json:"ready_timeout_ms,omitempty"`
	Runtime         *Runtime       `json:"runtime,omitempty"`
	Sandbox         *Sandbox       `json:"sandbox,omitempty"`
	VolumeMounts    *[]VolumeMount `json:"volume_mounts,omitempty"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code  ErrorCode `json:"code"`
	Error string    `json:"error"`
}

// EventType defines model for EventType.
type EventType string

// Limits defines model for Limits.
type Limits struct {
	CpuPeriodUs     *int64 `json:"cpu_period_us,omitempty"`
	CpuQuotaUs      *int64 `json:"cpu_quota_us,omitempty"`
	MemoryHighBytes *int64 `json:"memory_high_bytes,omitempty"`
	MemoryMaxBytes  *int64 `json:"memory_max_bytes,omitempty"`
	PidsMax         *int64 `json:"pids_max,omitempty"`
}

// ListAppsResponse defines model for ListAppsResponse.
type ListAppsResponse struct {
	Apps []AppView `json:"apps"`
}

// ListVolumesResponse defines model for ListVolumesResponse.
type ListVolumesResponse struct {
	Volumes []VolumeView `json:"volumes"`
}

// RestartRequest defines model for RestartRequest.
type RestartRequest struct {
	TimeoutMs *int64 `json:"timeout_ms,omitempty"`
}

// Runtime defines model for Runtime.
type Runtime string

// Sandbox defines model for Sandbox.
type Sandbox struct {
	Chroot         *string `json:"chroot,omitempty"`
	IpcNamespace   *bool   `json:"ipc_namespace,omitempty"`
	MountNamespace *bool   `json:"mount_namespace,omitempty"`
	NoNewPrivs     *bool   `json:"no_new_privs,omitempty"`
	PidNamespace   *bool   `json:"pid_namespace,omitempty"`
	UserNamespace  *bool   `json:"user_namespace,omitempty"`
	UtsNamespace   *bool   `json:"uts_namespace,omitempty"`
}

// SpawnRequest defines model for SpawnRequest.
type SpawnRequest struct {
	Args    *[]string `json:"args,omitempty"`
	Command *string   `json:"command,omitempty"`
	Entry   *string   `json:"entry,omitempty"`

	// Env KEY=VALUE pairs
	Env             *[]string      `json:"env,omitempty"`
	HealthCheckPath *string        `json:"health_check_path,omitempty"`
	Id              string         `json:"id"`
	Limits          *Limits        `json:"limits,omitempty"`
	NetIsolation    *bool          `json:"net_isolation,omitempty"`
	Port            int            `json:"port"`
	Runtime         *Runtime       `json:"runtime,omitempty"`
	Sandbox         *Sandbox       `json:"sandbox,omitempty"`
	VolumeMounts    *[]VolumeMount `json:"volume_mounts,omitempty"`
}

// StatsView defines model for StatsView.
type StatsView struct {
	CgroupEnabled      bool    `json:"cgroup_enabled"`
	CpuUsageUsec       *int64  `json:"cpu_usage_usec,omitempty"`
	Id                 string  `json:"id"`
	MemoryCurrentBytes *int64  `json:"memory_current_bytes,omitempty"`
	MemoryMaxBytes     *int64  `json:"memory_max_bytes,omitempty"`
	OomKills           *int64  `json:"oom_kills,omitempty"`
	PidsCurrent        *int64  `json:"pids_current,omitempty"`
	ReadErr            *string `json:"read_err,omitempty"`
}

// VolumeMount defines model for VolumeMount.
type VolumeMount struct {
	ReadOnly *bool   `json:"read_only,omitempty"`
	SubPath  *string `json:"sub_path,omitempty"`
	Target   string  `json:"target"`
	VolumeId string  `json:"volume_id"`
}

// VolumeRequest defines model for VolumeRequest.
type VolumeRequest struct {
	BackingPath string `json:"backing_path"`
	Id          string `json:"id"`
	ReadOnly    *bool  `json:"read_only,omitempty"`
}

// VolumeView defines model for VolumeView.
type VolumeView struct {
	BackingPath string  `json:"backing_path"`
	FsType      *string `json:"fs_type,omitempty"`
	Id          string  `json:"id"`
	ReadOnly    *bool   `json:"read_only,omitempty"`
}

// AppID defines model for AppID.
type AppID = string

// VolumeID defines model for VolumeID.
type VolumeID = string

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// GetAppLogsParams defines parameters for GetAppLogs.
type GetAppLogsParams struct {
	// Tail Number of lines from the end
	Tail *int `form:"tail,omitempty" json:"tail,omitempty"`

	// Follow Stream new lines as SSE events
	Follow *GetAppLogsParamsFollow `form:"follow,omitempty" json:"follow,omitempty"`
}

// GetAppLogsParamsFollow defines parameters for GetAppLogs.
type GetAppLogsParamsFollow string

// DeleteVolumeParams defines parameters for DeleteVolume.
type DeleteVolumeParams struct {
	// Force Force delete even if apps reference this volume
	Force *DeleteVolumeParamsForce `form:"force,omitempty" json:"force,omitempty"`
}

// DeleteVolumeParamsForce defines parameters for DeleteVolume.
type DeleteVolumeParamsForce string

// SpawnAppJSONRequestBody defines body for SpawnApp for application/json ContentType.
type SpawnAppJSONRequestBody = SpawnRequest

// DeployAppJSONRequestBody defines body for DeployApp for application/json ContentType.
type DeployAppJSONRequestBody = DeployRequest

// RestartAppJSONRequestBody defines body for RestartApp for application/json ContentType.
type RestartAppJSONRequestBody = RestartRequest

// RegisterVolumeJSONRequestBody defines body for RegisterVolume for application/json ContentType.
type RegisterVolumeJSONRequestBody = VolumeRequest
