// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package apitypes

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for AppApiVersion.
const (
	CreekDevv1alpha1 AppApiVersion = "creek.dev/v1alpha1"
)

// Valid indicates whether the value is a known member of the AppApiVersion enum.
func (e AppApiVersion) Valid() bool {
	switch e {
	case CreekDevv1alpha1:
		return true
	default:
		return false
	}
}

// Defines values for AppKind.
const (
	AppKindApp AppKind = "App"
)

// Valid indicates whether the value is a known member of the AppKind enum.
func (e AppKind) Valid() bool {
	switch e {
	case AppKindApp:
		return true
	default:
		return false
	}
}

// Defines values for AppViewStatus.
const (
	AppViewStatusCrashLooping AppViewStatus = "crash-looping"
	AppViewStatusCrashed      AppViewStatus = "crashed"
	AppViewStatusRunning      AppViewStatus = "running"
	AppViewStatusStarting     AppViewStatus = "starting"
	AppViewStatusStopped      AppViewStatus = "stopped"
	AppViewStatusUnhealthy    AppViewStatus = "unhealthy"
	AppViewStatusUnknown      AppViewStatus = "unknown"
)

// Valid indicates whether the value is a known member of the AppViewStatus enum.
func (e AppViewStatus) Valid() bool {
	switch e {
	case AppViewStatusCrashLooping:
		return true
	case AppViewStatusCrashed:
		return true
	case AppViewStatusRunning:
		return true
	case AppViewStatusStarting:
		return true
	case AppViewStatusStopped:
		return true
	case AppViewStatusUnhealthy:
		return true
	case AppViewStatusUnknown:
		return true
	default:
		return false
	}
}

// Defines values for ConditionStatus.
const (
	ConditionStatusFalse   ConditionStatus = "False"
	ConditionStatusTrue    ConditionStatus = "True"
	ConditionStatusUnknown ConditionStatus = "Unknown"
)

// Valid indicates whether the value is a known member of the ConditionStatus enum.
func (e ConditionStatus) Valid() bool {
	switch e {
	case ConditionStatusFalse:
		return true
	case ConditionStatusTrue:
		return true
	case ConditionStatusUnknown:
		return true
	default:
		return false
	}
}

// Defines values for ConditionType.
const (
	ConditionTypeBackupReady ConditionType = "BackupReady"
	ConditionTypeDegraded    ConditionType = "Degraded"
	ConditionTypeProgressing ConditionType = "Progressing"
	ConditionTypeReady       ConditionType = "Ready"
)

// Valid indicates whether the value is a known member of the ConditionType enum.
func (e ConditionType) Valid() bool {
	switch e {
	case ConditionTypeBackupReady:
		return true
	case ConditionTypeDegraded:
		return true
	case ConditionTypeProgressing:
		return true
	case ConditionTypeReady:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	ErrorCodeAlreadyRunning          ErrorCode = "already_running"
	ErrorCodeBadRequest              ErrorCode = "bad_request"
	ErrorCodeConflict                ErrorCode = "conflict"
	ErrorCodeDeployUnhealthy         ErrorCode = "deploy_unhealthy"
	ErrorCodeInternal                ErrorCode = "internal"
	ErrorCodeInvalidId               ErrorCode = "invalid_id"
	ErrorCodeInvalidRuntime          ErrorCode = "invalid_runtime"
	ErrorCodeNotFound                ErrorCode = "not_found"
	ErrorCodePortConflict            ErrorCode = "port_conflict"
	ErrorCodeResourceVersionMismatch ErrorCode = "resource_version_mismatch"
	ErrorCodeStorageCorrupted        ErrorCode = "storage_corrupted"
	ErrorCodeUnauthorized            ErrorCode = "unauthorized"
	ErrorCodeUnsupportedFilesystem   ErrorCode = "unsupported_filesystem"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case ErrorCodeAlreadyRunning:
		return true
	case ErrorCodeBadRequest:
		return true
	case ErrorCodeConflict:
		return true
	case ErrorCodeDeployUnhealthy:
		return true
	case ErrorCodeInternal:
		return true
	case ErrorCodeInvalidId:
		return true
	case ErrorCodeInvalidRuntime:
		return true
	case ErrorCodeNotFound:
		return true
	case ErrorCodePortConflict:
		return true
	case ErrorCodeResourceVersionMismatch:
		return true
	case ErrorCodeStorageCorrupted:
		return true
	case ErrorCodeUnauthorized:
		return true
	case ErrorCodeUnsupportedFilesystem:
		return true
	default:
		return false
	}
}

// Defines values for EventType.
const (
	EventTypeHealthFailure EventType = "health_failure"
	EventTypeOomKill       EventType = "oom_kill"
	EventTypeReady         EventType = "ready"
	EventTypeRestart       EventType = "restart"
	EventTypeStatusChanged EventType = "status_changed"
)

// Valid indicates whether the value is a known member of the EventType enum.
func (e EventType) Valid() bool {
	switch e {
	case EventTypeHealthFailure:
		return true
	case EventTypeOomKill:
		return true
	case EventTypeReady:
		return true
	case EventTypeRestart:
		return true
	case EventTypeStatusChanged:
		return true
	default:
		return false
	}
}

// Defines values for Runtime.
const (
	Bun  Runtime = "bun"
	Deno Runtime = "deno"
	Node Runtime = "node"
)

// Valid indicates whether the value is a known member of the Runtime enum.
func (e Runtime) Valid() bool {
	switch e {
	case Bun:
		return true
	case Deno:
		return true
	case Node:
		return true
	default:
		return false
	}
}

// Defines values for GetAppLogsParamsFollow.
const (
	True GetAppLogsParamsFollow = "true"
)

// Valid indicates whether the value is a known member of the GetAppLogsParamsFollow enum.
func (e GetAppLogsParamsFollow) Valid() bool {
	switch e {
	case True:
		return true
	default:
		return false
	}
}

// App K8s-style resource envelope. See DESIGN-self-host-state.md
// "The interop-bearing subset" for the field semantics.
type App struct {
	ApiVersion AppApiVersion `json:"apiVersion"`
	Kind       AppKind       `json:"kind"`
	Metadata   AppMetadata   `json:"metadata"`

	// Spec Desired state. Settable by clients.
	Spec AppSpec `json:"spec"`

	// Status Observed state. Server-written; clients receive 405 on writes.
	Status AppStatus `json:"status"`
}

// AppApiVersion defines model for App.ApiVersion.
type AppApiVersion string

// AppKind defines model for App.Kind.
type AppKind string

// AppEvent defines model for AppEvent.
type AppEvent struct {
	AppId          string    `json:"app_id"`
	HealthFailures *int64    `json:"health_failures,omitempty"`
	Pid            *int      `json:"pid,omitempty"`
	Port           *int      `json:"port,omitempty"`
	RestartCount   *int      `json:"restart_count,omitempty"`
	Status         *string   `json:"status,omitempty"`
	Ts             time.Time `json:"ts"`
	Type           EventType `json:"type"`
	Url            *string   `json:"url,omitempty"`
}

// AppMetadata defines model for AppMetadata.
type AppMetadata struct {
	// CreationTimestamp RFC3339. Immutable; preserved across restore.
	CreationTimestamp time.Time `json:"creationTimestamp"`

	// Generation Bumps on every successful spec write. NOT bumped on status, annotations, or labels.
	Generation int64 `json:"generation"`

	// Name Human-readable ID, [a-z0-9-] 1-63 chars.
	Name string `json:"name"`

	// ResourceVersion Opaque CAS token. Clients MUST NOT do arithmetic on it.
	ResourceVersion string `json:"resourceVersion"`

	// Uid UUIDv7. Stable across rename; never reused.
	Uid openapi_types.UUID `json:"uid"`
}

// AppSpec Desired state. Settable by clients.
type AppSpec struct {
	Args    *[]string `json:"args,omitempty"`
	Command *string   `json:"command,omitempty"`
	Env     *[]string `json:"env,omitempty"`
	Port    *int      `json:"port,omitempty"`
	Runtime *string   `json:"runtime,omitempty"`
}

// AppStatus Observed state. Server-written; clients receive 405 on writes.
type AppStatus struct {
	// Conditions Closed set of observed condition types: Ready, Progressing,
	// Degraded, BackupReady. Recomputed at GET time from supervisor
	// runtime state. The set is fixed in v1alpha1 — adding a new
	// condition type requires an ADR.
	Conditions     []Condition `json:"conditions"`
	CurrentPid     int         `json:"currentPid"`
	CurrentPort    int         `json:"currentPort"`
	HealthFailures int64       `json:"healthFailures"`
	NetIp          *string     `json:"netIp,omitempty"`

	// ObservedGeneration Last spec generation the deploy flow has converged to a healthy state on.
	ObservedGeneration int64 `json:"observedGeneration"`
	RestartCount       int   `json:"restartCount"`
	UptimeMs           int64 `json:"uptimeMs"`
}

// AppView defines model for AppView.
type AppView struct {
	Args           *[]string     `json:"args,omitempty"`
	Command        string        `json:"command"`
	Env            *[]string     `json:"env,omitempty"`
	HealthFailures int64         `json:"health_failures"`
	Id             string        `json:"id"`
	NetIp          *string       `json:"net_ip,omitempty"`
	Pid            int           `json:"pid"`
	Port           int           `json:"port"`
	RestartCount   int           `json:"restart_count"`
	Runtime        *Runtime      `json:"runtime,omitempty"`
	Status         AppViewStatus `json:"status"`
	UptimeMs       int64         `json:"uptime_ms"`
}

// AppViewStatus defines model for AppView.Status.
type AppViewStatus string

// Condition Status of one named runtime condition. Mirrors the K8s
// condition tuple: a closed type vocabulary, tri-state status
// (True / False / Unknown), and the timestamp of the last
// observed transition. `reason` is a CamelCase token for
// machine consumption; `message` is human-readable.
type Condition struct {
	LastTransitionTime time.Time       `json:"lastTransitionTime"`
	Message            *string         `json:"message,omitempty"`
	Reason             string          `json:"reason"`
	Status             ConditionStatus `json:"status"`
	Type               ConditionType   `json:"type"`
}

// ConditionStatus defines model for Condition.Status.
type ConditionStatus string

// ConditionType defines model for Condition.Type.
type ConditionType string

// DeployRequest defines model for DeployRequest.
type DeployRequest struct {
	Args            *[]string      `json:"args,omitempty"`
	Command         *string        `json:"command,omitempty"`
	Entry           *string        `json:"entry,omitempty"`
	Env             *[]string      `json:"env,omitempty"`
	GracefulV1Ms    *int64         `json:"graceful_v1_ms,omitempty"`
	HealthCheckPath *string        `json:"health_check_path,omitempty"`
	Limits          *Limits        `json:"limits,omitempty"`
	NetIsolation    *bool          `json:"net_isolation,omitempty"`
	PollIntervalMs  *int64         `json:"poll_interval_ms,omitempty"`
	Port            int            `json:"port"`
	ReadyTimeoutMs  *int64         `json:"ready_timeout_ms,omitempty"`
	Runtime         *Runtime       `json:"runtime,omitempty"`
	Sandbox         *Sandbox       `json:"sandbox,omitempty"`
	VolumeMounts    *[]VolumeMount `json:"volume_mounts,omitempty"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code  ErrorCode `json:"code"`
	Error string    `json:"error"`
}

// EventType defines model for EventType.
type EventType string

// Limits defines model for Limits.
type Limits struct {
	CpuPeriodUs     *int64 `json:"cpu_period_us,omitempty"`
	CpuQuotaUs      *int64 `json:"cpu_quota_us,omitempty"`
	MemoryHighBytes *int64 `json:"memory_high_bytes,omitempty"`
	MemoryMaxBytes  *int64 `json:"memory_max_bytes,omitempty"`
	PidsMax         *int64 `json:"pids_max,omitempty"`
}

// ListAppsResponse defines model for ListAppsResponse.
type ListAppsResponse struct {
	Apps []AppView `json:"apps"`
}

// ListVolumesResponse defines model for ListVolumesResponse.
type ListVolumesResponse struct {
	Volumes []VolumeView `json:"volumes"`
}

// RestartRequest defines model for RestartRequest.
type RestartRequest struct {
	TimeoutMs *int64 `json:"timeout_ms,omitempty"`
}

// Runtime defines model for Runtime.
type Runtime string

// Sandbox defines model for Sandbox.
type Sandbox struct {
	Chroot         *string `json:"chroot,omitempty"`
	IpcNamespace   *bool   `json:"ipc_namespace,omitempty"`
	MountNamespace *bool   `json:"mount_namespace,omitempty"`
	NoNewPrivs     *bool   `json:"no_new_privs,omitempty"`
	PidNamespace   *bool   `json:"pid_namespace,omitempty"`
	UserNamespace  *bool   `json:"user_namespace,omitempty"`
	UtsNamespace   *bool   `json:"uts_namespace,omitempty"`
}

// SpawnRequest defines model for SpawnRequest.
type SpawnRequest struct {
	Args    *[]string `json:"args,omitempty"`
	Command *string   `json:"command,omitempty"`
	Entry   *string   `json:"entry,omitempty"`

	// Env KEY=VALUE pairs
	Env             *[]string      `json:"env,omitempty"`
	HealthCheckPath *string        `json:"health_check_path,omitempty"`
	Id              string         `json:"id"`
	Limits          *Limits        `json:"limits,omitempty"`
	NetIsolation    *bool          `json:"net_isolation,omitempty"`
	Port            int            `json:"port"`
	Runtime         *Runtime       `json:"runtime,omitempty"`
	Sandbox         *Sandbox       `json:"sandbox,omitempty"`
	VolumeMounts    *[]VolumeMount `json:"volume_mounts,omitempty"`
}

// StatsView defines model for StatsView.
type StatsView struct {
	CgroupEnabled      bool    `json:"cgroup_enabled"`
	CpuUsageUsec       *int64  `json:"cpu_usage_usec,omitempty"`
	Id                 string  `json:"id"`
	MemoryCurrentBytes *int64  `json:"memory_current_bytes,omitempty"`
	MemoryMaxBytes     *int64  `json:"memory_max_bytes,omitempty"`
	OomKills           *int64  `json:"oom_kills,omitempty"`
	PidsCurrent        *int64  `json:"pids_current,omitempty"`
	ReadErr            *string `json:"read_err,omitempty"`
}

// VolumeMount defines model for VolumeMount.
type VolumeMount struct {
	ReadOnly *bool   `json:"read_only,omitempty"`
	SubPath  *string `json:"sub_path,omitempty"`
	Target   string  `json:"target"`
	VolumeId string  `json:"volume_id"`
}

// VolumeRequest defines model for VolumeRequest.
type VolumeRequest struct {
	BackingPath string `json:"backing_path"`
	Id          string `json:"id"`
	ReadOnly    *bool  `json:"read_only,omitempty"`
}

// VolumeView defines model for VolumeView.
type VolumeView struct {
	BackingPath string  `json:"backing_path"`
	FsType      *string `json:"fs_type,omitempty"`
	Id          string  `json:"id"`
	ReadOnly    *bool   `json:"read_only,omitempty"`
}

// AppID defines model for AppID.
type AppID = string

// VolumeID defines model for VolumeID.
type VolumeID = string

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// PreconditionFailed defines model for PreconditionFailed.
type PreconditionFailed = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// StopAppParams defines parameters for StopApp.
type StopAppParams struct {
	// IfMatch Current resourceVersion (opaque). Mismatch yields 412.
	IfMatch *string `json:"If-Match,omitempty"`
}

// DeployAppParams defines parameters for DeployApp.
type DeployAppParams struct {
	// IfMatch Current resourceVersion (opaque). Mismatch yields 412.
	IfMatch *string `json:"If-Match,omitempty"`
}

// GetAppLogsParams defines parameters for GetAppLogs.
type GetAppLogsParams struct {
	// Tail Number of lines from the end
	Tail *int `form:"tail,omitempty" json:"tail,omitempty"`

	// Follow Stream new lines as SSE events
	Follow *GetAppLogsParamsFollow `form:"follow,omitempty" json:"follow,omitempty"`
}

// GetAppLogsParamsFollow defines parameters for GetAppLogs.
type GetAppLogsParamsFollow string

// DeleteVolumeParams defines parameters for DeleteVolume.
type DeleteVolumeParams struct {
	// Force Force delete even if apps reference this volume
	Force *bool `form:"force,omitempty" json:"force,omitempty"`
}

// SpawnAppJSONRequestBody defines body for SpawnApp for application/json ContentType.
type SpawnAppJSONRequestBody = SpawnRequest

// DeployAppJSONRequestBody defines body for DeployApp for application/json ContentType.
type DeployAppJSONRequestBody = DeployRequest

// RestartAppJSONRequestBody defines body for RestartApp for application/json ContentType.
type RestartAppJSONRequestBody = RestartRequest

// RegisterVolumeJSONRequestBody defines body for RegisterVolume for application/json ContentType.
type RegisterVolumeJSONRequestBody = VolumeRequest
