package lima

import (
	"fmt"
	"os"
	"strings"
)

type PortForward struct {
	Guest int
	Host  int
}

type VMConfig struct {
	CPUs   int
	Memory string
	Disk   string
	Ports  []PortForward
}

func DefaultConfig() VMConfig {
	return VMConfig{
		CPUs:   2,
		Memory: "2GiB",
		Disk:   "10GiB",
		Ports: []PortForward{
			{Guest: 3000, Host: 13000},
			{Guest: 9090, Host: 19090},
		},
	}
}

var primitivePorts = map[string]PortForward{
	"postgres": {Guest: 5432, Host: 15432},
	"redis":    {Guest: 6379, Host: 16379},
}

func (c *VMConfig) AddPrimitive(name string) {
	if pf, ok := primitivePorts[name]; ok {
		for _, existing := range c.Ports {
			if existing.Guest == pf.Guest {
				return
			}
		}
		c.Ports = append(c.Ports, pf)
	}
}

func (c *VMConfig) Render() string {
	var b strings.Builder

	b.WriteString("# Generated by creekd sandbox — do not edit\n")
	b.WriteString("\n")
	b.WriteString("images:\n")
	b.WriteString("  - location: \"https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-amd64.img\"\n")
	b.WriteString("    arch: \"x86_64\"\n")
	b.WriteString("  - location: \"https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-arm64.img\"\n")
	b.WriteString("    arch: \"aarch64\"\n")
	b.WriteString("\n")
	fmt.Fprintf(&b, "cpus: %d\n", c.CPUs)
	fmt.Fprintf(&b, "memory: %q\n", c.Memory)
	fmt.Fprintf(&b, "disk: %q\n", c.Disk)
	b.WriteString("\n")
	b.WriteString("mounts:\n")
	b.WriteString("  - location: \"~\"\n")
	b.WriteString("    writable: false\n")
	b.WriteString("\n")
	b.WriteString("containerd:\n")
	b.WriteString("  system: false\n")
	b.WriteString("  user: false\n")
	b.WriteString("\n")
	b.WriteString("provision:\n")
	b.WriteString("  - mode: system\n")
	b.WriteString("    script: |\n")
	b.WriteString("      #!/bin/bash\n")
	b.WriteString("      set -eux\n")
	b.WriteString("      export DEBIAN_FRONTEND=noninteractive\n")
	b.WriteString("      apt-get update\n")
	b.WriteString("      apt-get install -y --no-install-recommends curl unzip ca-certificates gnupg lsb-release python3 sqlite3\n")

	if len(c.Ports) > 0 {
		b.WriteString("\nportForwards:\n")
		for _, pf := range c.Ports {
			fmt.Fprintf(&b, "  - guestPort: %d\n", pf.Guest)
			fmt.Fprintf(&b, "    hostPort: %d\n", pf.Host)
			b.WriteString("    proto: tcp\n")
		}
	}

	return b.String()
}

func (c *VMConfig) WriteTo(path string) error {
	return os.WriteFile(path, []byte(c.Render()), 0644)
}
